### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by TAdamSmith** [766F6964/mublog#25]
I think this program should support dark mode. A toggle switch would require JavaScript so a change in the python file, or even better, creating a config.yml file with more customization options would be great.

**Comment by 766F6964** [comment]
While I don't want to provide extensive theming support, I think having a light and a dark theme to chose might not be a bad idea.
To add this feature, I could see the following approach work nicely:

- Introduce two distinct color themes (dark and light) in the `style.css` file.
- Introduce a configuration option in `mublog.py` to allow users to specify their preferred color scheme as the default.
- Introduce a configuration option in `mublog.py` to enable a toggle button on the blog site, allowing users to switch between the dark and light theme. (Note: This functionality will require JavaScript)

I don't plan to support more extensive theming, like custom colors, different layouts or animations.
If one wants these features, I expect them to modify the relevant files themselves, which should be relatively straightforward.

However, this feature will have to wait a bit. I plan to rework the current implementation for the blog configuration options first.

**Comment by 766F6964** [comment]
Added in #43 and will be part of the next release.

**Comment by 766F6964** [comment]
Completed with and #43 and #45.
