### ISSUE TITLE
Support for RSS

### ISSUE THREAD

**Issue by 766F6964** [766F6964/mublog#3]
**Summary**
It would be nice to automatically generate an RSS feed.
A lot of people use RSS to read blogs, so it would be a good addition.

**Notes:**
We have to check how accurate time stamps need to be. Currently each post only has a date assign, but not time.
Unsure how this affects RSS polling, in terms of when a post is considered "new".

**Comment by 766F6964** [comment]
All links to assets etc need to be absolute links. Otherwise they wont load in the rss clients.

**Comment by 766F6964** [comment]
Optionally, feed items can contain a guid tag to uniquely identify an item.
If not present, most feed readers will use the link or the content instead. 
However, this could results in an item showing up as new, if the link or the content of the item changes.
It might be worth supporting this tag. More information: https://www.w3schools.com/xml/rss_tag_guid.asp

Side note: Maybe instead of an absolute link, the filename could be used instead? Then changing e.g. the domain of the blog wouldn't result in a problem. Unsure if that is an ideal solution, more research required.

**Comment by TAdamSmith** [comment]
It would be great!

**Comment by 766F6964** [comment]
Experimental support has been added with #26.
I'll close this issue for now, but I am sure further changes and refinements of the rss feature will be coming in the future.
