### ISSUE TITLE
Add template directory

### ISSUE THREAD

**Issue by 766F6964** [766F6964/mublog#4]
**Summary:**
We have a lot of files, in which we perform substitutions (such as the HTML header and footer), but also the tags js file etc.
Instead of having so many hardcoded strings, that get written as file, it might be sensible to have a template directory, that stores these templates, and the script just loads all the content from there.

Then we should also have some helper functions like `replace_str(pattern, new_value)`, to prevent code duplication

**Comment by KubaO** [comment]
Something like this?

https://github.com/KubaO/mublog-py/commit/4c92150e0ee8212c331a32c03bb3b6d8184c26bc

I don't particularly like adding an html file as a template - should it be perhaps md and treated just like other md files?

**Comment by 766F6964** [comment]
Completed with https://github.com/766F6964/mublog/pull/7
